--- 
 - hosts: webservers 
   become: yes
   roles: 
     - java
     - nginx
   vars:   
      java_packages:  java-1.7.0-openjdk  

 - hosts: dbservers
   become: yes
   roles:
     - postgres
 - hosts: loadbalancers
   become: yes
   roles: 
     - haproxy
 - hosts: webservers
   become: yes
   become_user: ansible
   roles: 
     - appsetup 
